name: businessy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  responsive_framework: ^0.1.6 
  charts_flutter: ^0.11.0
  fl_chart: ^0.67.0  
  curved_navigation_bar: ^1.0.0 
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/logo.png
  - assets/img/google_logo.png
  - assets/img/upload.png
 

